version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - 8080:80
    container_name: web
    hostname: web
    networks:
      - myweb
    labels:
      - traefik.web.frontend.rule=Host:myweb
      - traefik.web.port=80
      - traefik.docker.network=myweb

networks:
  myweb:
    external: true
